### ISSUE TITLE
The map doesnt start automatically and the aperture overlay makes surface portalable

### ISSUE THREAD

**Issue by Scipply** [Portal-2-Multiplayer-Mod/Portal-2-Multiplayer-Mod#100]
I'm too lazy to submit 2 issues separately when one of them can be fixed easily. I'm just going to submit 3 images bc there is probably no need for any other info except for the fact that the aperture overlay is for some reason making the surface portalable
![Screenshot-2023-12-09-200959 875](https://github.com/Portal-2-Multiplayer-Mod/Portal-2-Multiplayer-Mod/assets/69108329/77717d67-1223-457b-84b0-e79d240e9d45)
![Screenshot-2023-12-09-195101 476](https://github.com/Portal-2-Multiplayer-Mod/Portal-2-Multiplayer-Mod/assets/69108329/fa7c56b5-8924-4cbf-825c-b3d20a6a6966)
![Screenshot-2023-12-22-090652 252](https://github.com/Portal-2-Multiplayer-Mod/Portal-2-Multiplayer-Mod/assets/69108329/31e155e0-c374-4d93-84b6-44829e81b2c3)

**Comment by OrsellGaming** [comment]
Ok so it's not automatically starting because it's missing the `_` in the custom launch options between `lobby` and `3`. Simple user error. As for portalling in the surface, that's a bug that I don't think we can fix, we don't know why that's happening anyway. Not too big of a issue.

**Comment by OrsellGaming** [comment]
In fact, in the last image you sent, it says what it should be. It seems you've just accidentally removed the `_`. This issue will now be closed.
