### ISSUE TITLE
Add the ability to add P2MM Launcher as a Non-Steam game to Steam with P2MM Steam Artwork

### ISSUE THREAD

**Issue by OrsellGaming** [Portal-2-Multiplayer-Mod/Portal-2-Multiplayer-Mod#104]
Add the ability to add P2MM Launcher as a Non-Steam game to Steam with P2MM Steam Artwork. It would be excellent for ease of access to have the launcher add itself as a non-Steam game to Steam at the user's choice. We also have our own artwork and other assets that work with the Steams library system, so we should be able to add that along with the launcher. I plan to implement this like other applications like SteamROMManager, which does the same thing but with emulators.

**Comment by BassHoven** [comment]
You can do this, you need to go to steam

**Comment by OrsellGaming** [comment]
This is an automatic process with a button in the launcher, not the manual one in Steam itself.

**Comment by BassHoven** [comment]
Ohhh
I will look into it, try to see what can i do

**Comment by OrsellGaming** [comment]
Closing, don't plan to do this anymore.

**Comment by nightwatchmaker** [comment]
i added it to my steam library
