### ISSUE TITLE
[Suggestion] Use a better alternative instead of PyInstaller

### ISSUE THREAD

**Issue by dnchshrp** [Portal-2-Multiplayer-Mod/Portal-2-Multiplayer-Mod#112]
Hi! In your README file you told that 

> (if you know of better options please tell us)

, so here's one:

https://nuitka.net/
Instead of packaging the app with a Python runtime like PyInstaller it converts the Python code to C and compiles it into binaries

**Comment by cabiste69** [comment]
thanks for the recommendation, we'll try it and tell you the results 🫡

**Comment by dnchshrp** [comment]
Also because it converts the code to C using it _may_ result in better server performance

**Comment by OrsellGaming** [comment]
If you're referring to Portal 2 itself, that's separate from the launcher. The launcher simply mounts files onto the game as well as configures a few things, and then launches the game.

**Comment by OrsellGaming** [comment]
Using alternative as of `2.2.2` referenced in PR: https://github.com/Portal-2-Multiplayer-Mod/Portal-2-Multiplayer-Mod/pull/123

**Comment by dnchshrp** [comment]
Great!
