### ISSUE TITLE
Make the launcher hide in the tray after you launch the game

### ISSUE THREAD

**Issue by scipply** [Portal-2-Multiplayer-Mod/Portal-2-Multiplayer-Mod#114]
I think it would be really good to hide the launcher in the tray when the game is running. It could open a menu with stuff like Run concommand as server... , Change map to... , Go to lobby, Restart map, Show logs, Show server console, Open Launcher, etc. , and if you click on it twice, it would open the launcher. The menu would be cool but the "Hide to tray" would be a Quality of life feature hehe

**Comment by scipply** [comment]
no triage access :c

**Comment by OrsellGaming** [comment]
The launcher does not have any proper way to communicate with the game to do certain actions like ypu said. The easiest way to do the things you mentioned would to just use chat commands or press ` on your keyboard to open the console.

I could look into making it a tray thing just in general.

**Comment by OrsellGaming** [comment]
Won't be implementing this feature. It's not necessarily needed, plus most of the features requested can already be easily done in-game. Also, it would require a lot of extra work to get Portal 2 and the launcher to communicate properly, and I've already tried doing that in the past. It didn't fair well. Closing.
