### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by Temporary50** [Portal-2-Multiplayer-Mod/Portal-2-Multiplayer-Mod#115]
My Windows Defender software says it's a virus and an attacker is using commands to get personal info. I WON'T FRICKING USE THIS ANYMORE!!!!!!!!

**Comment by Temporary50** [comment]
think so

**Comment by Temporary50** [comment]
If my Defender software says it hates it, I'm going with it. :(

**Comment by Temporary50** [comment]
should fix

**Comment by Temporary50** [comment]
o

**Comment by Temporary50** [comment]
ok

**Comment by OrsellGaming** [comment]
@Temporary50 My guy, if you read our FAQ or even seen that our software is open source, you can tell this isnt a virus. All our code is publically avaliable. It gets flagged because pyinstaller, the compiler we use, gets flagged by Windows Defender.

**Comment by OrsellGaming** [comment]
@Temporary50  I’m going to close this issue. If you need help, please look at our [wiki](https://github.com/Portal-2-Multiplayer-Mod/Portal-2-Multiplayer-Mod/wiki) or go make a help post in our [discord server](https://discord.com/invite/kW3nG6GKpF).

**Comment by OrsellGaming** [comment]
@Back-Slash-N please stop and dont do that. Clearly this person has not uaed github before.
