### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by Temporary50** [Portal-2-Multiplayer-Mod/Portal-2-Multiplayer-Mod#116]
The game crashes in SPchapter 1 when you go down the incenerator, the game crashes. In SPchapter 9, when you go through the door to get out of the "death trap" room, the game crashes.

Anyways, please fix them!

**Comment by OrsellGaming** [comment]
Is your install of the mod fully up to date? Because this issue has already have been fixed.

**Comment by OrsellGaming** [comment]
@Temporary50

**Comment by OrsellGaming** [comment]
So @Temporary50 has the problem been solved?

**Comment by Temporary50** [comment]
NOPE

**Comment by Temporary50** [comment]
frick. this. mod.
CREATORS!

**Comment by OrsellGaming** [comment]
Ok, first of all, you aren't giving us any time to fix the issue before declaring this a bad mod. You've proven to jump to conclusions, especially when you posted about this being a virus #115. So before you run off let me fix this so you can run the mod.

**Comment by cabiste69** [comment]
> frick. this. mod. CREATORS!

🗣️💨
