### ISSUE TITLE
Make the !help command run automatically when the lobby map loads

### ISSUE THREAD

**Issue by scipply** [Portal-2-Multiplayer-Mod/Portal-2-Multiplayer-Mod#121]
Bc ppl often ask "How can me run chat commands??? Should me put it in the console?"

**Comment by OrsellGaming** [comment]
The feature has been added in commit https://github.com/OrsellGaming/Portal-2-Multiplayer-Mod-Plugin/commit/352d0ad02ff5a5debccf7b8df0eca0ef3d5a9ec5 and commit https://github.com/Portal-2-Multiplayer-Mod/Portal-2-Multiplayer-Mod/commit/47d8ade1163d0eccffbfde5869bc88276c2d3916
