### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by nightwatchmaker** [Portal-2-Multiplayer-Mod/Portal-2-Multiplayer-Mod#128]
When you update the launcher it doesn't work anymore

**Comment by OrsellGaming** [comment]
You need to elaborate more on what's wrong and also provide a log from the launcher for me to be able to help you.

**Comment by OrsellGaming** [comment]
Closing issue as the issue opener hasn't provided any details on the issue and is not responding.

**Comment by nightwatchmaker** [comment]
nevermind it works it just 85% of the time will crash and it goes SLOW when it actually works
