### ISSUE TITLE
No steam logon

### ISSUE THREAD

**Issue by nightwatchmaker** [Portal-2-Multiplayer-Mod/Portal-2-Multiplayer-Mod#131]
I get no steam logon kick like every 2 or 1 minutes i play with someone else with this mod.

Edit: It now does the no steam logon kick in other games like aperture tag without mod.

**Comment by OrsellGaming** [comment]
Please check the FAQ for more information.

**Comment by OrsellGaming** [comment]
Closing, solution to issue is in the FAQ.
