### ISSUE TITLE
sp_a2_pit_flings mapsupport issue

### ISSUE THREAD

**Issue by Nanoman2525** [Portal-2-Multiplayer-Mod/Portal-2-Multiplayer-Mod#45]
If you trigger the ending dialogue and then someone fizzles a cube, the elevator will never come down.

**Comment by OrsellGaming** [comment]
This seems and appears to be fixed, I am still waiting for total confirmation from @Nanoman2525 . The platform has been set to be permanently open, so I'm assuming this was the fix. Also, the func_clip_vphyiscs at the end isn't removed, so the trigger can't fizzle the cube. On top of that, both trigger_catapults, where the player launches themselves, is fizzling the cube when it touches it. Oddly, though, these two things aren't reflected in the VScript itself, very odd. Again, assuming it's fixed, so now I'm closing this issue.
