### ISSUE TITLE
Finish getting FastDL working for listen servers

### ISSUE THREAD

**Issue by OrsellGaming** [Portal-2-Multiplayer-Mod/Portal-2-Multiplayer-Mod#76]
Currently, the Python that creates the FastDL Server works as intended and can run on port 27016. Other ports have yet to be tested, but it's preferred to use 27016 because it is an available port for Source servers. Plus, we recommend opening the port because sometimes the listen server uses it if another listen server instance is somehow detected from the same host, a simple bug, but hopefully, it won't interfere with the FastDL Server that is running on the port also.

Testing also needs to be done to ensure the local FastDL HTTP Server is working as intended and can retrieve map files and other custom assets.

A current bug that is currently occurring is that after another map change is called, the game crashes.

**Comment by OrsellGaming** [comment]
@cabiste69 Why is this not planned? It should work as intended I just need to test it with a source map.

**Comment by cabiste69** [comment]
we decided the scrap it and focus on rewriting the mod

**Comment by OrsellGaming** [comment]
What do you mean scraped? We fixed FastDL so we need to implement it for listen servers somehow.

**Comment by cabiste69** [comment]
again both "FastDL" and "listen servers" are scrapped
