### ISSUE TITLE
Fix on screen keyboard inputs on Steam Deck not being detected properly

### ISSUE THREAD

**Issue by OrsellGaming** [Portal-2-Multiplayer-Mod/Portal-2-Multiplayer-Mod#80]

**Comment by cabiste69** [comment]
@OrsellGaming what's the progress on this? or should it be closed?

**Comment by OrsellGaming** [comment]
The issue was determined not as a bug in pygame, but how Valve handled Desktop and Gaming Mode inputs on the Steam Deck. Valve sets the Steam Decks controls through a .vdf file, which sets what buttons on the device do what. It will be changed for the Steam Decks controls to primarily be used in Gaming Mode, and it will just be recommended to use a keyboard and mouse for Desktop Mode.
