### ISSUE TITLE
"Get Level command" button doesnt work properly, how has no one noticed this

### ISSUE THREAD

**Issue by Back-Slash-N** [Portal-2-Multiplayer-Mod/Portal-2-Multiplayer-Mod#85]
(you paste in https://steamcommunity.com/sharedfiles/filedetails/?id=3000958528 for example)

### expected behavior
P2MM puts `changelevel workshop\2008091208048530042\open_world_1` in your clipboard

### what actually happens
P2MM puts `changelevel workshop\2008091208048530042\open_world_1.bsp` in your clipboard

putting .bsp at the end of changelevel does not work. the game does it for you. idk who tested this feature with testmap.bsp.bsp

**Comment by cabiste69** [comment]
that got fixed in 840176885e8cd24b96411fa705f199524d0e5c8f
