### ISSUE TITLE
when i load in and to place a portal it shoots from the back of my head and collides with me so i cant place portals

### ISSUE THREAD

**Issue by J3RKF4C3** [Portal-2-Multiplayer-Mod/Portal-2-Multiplayer-Mod#92]
i couldnt just put the video file here so i had to zip it so you can download it its an mkv file btw
[Video file in here.zip](https://github.com/Portal-2-Multiplayer-Mod/Portal-2-Multiplayer-Mod/files/13196704/Video.file.in.here.zip)

**Comment by OrsellGaming** [comment]
@J3RKF4C3 what you are experiencing is not the portal colliding with the player, but a trigger_portal_cleanser valve put in the map that we forgot to tell our code to remove. We have updated our code already to fix this and will not be issue in version 2.2. If you want a easy temporary fix, use the console command `ent_removeall trigger_portal_cleanser`. This should remove the nuisance triggers. You can use our code from the finalcleanup branch in this repository. Which includes other new goodies we've been working on, also it would be nice to have somebody not on the dev team to test it so we know it works for the end user.

**Comment by OrsellGaming** [comment]
Closing this as I gave a temporary solution to the problem and this issue has already been fixed for version 2.2.0.
